name-template: 'v$RESOLVED_VERSION-dev'
tag-template: 'v$RESOLVED_VERSION-dev'
prerelease: true
include-pre-releases: true
categories:
  - title: 'Major Changes'
    labels: ['Major']
  - title: 'Features'
    labels: ['Enhancement', 'Feature', 'Dev Task']
  - title: 'Bug Fixes'
    labels: ['Bug', 'Hot Fix', 'Task']
version-resolver:
  major:
    labels: ['Major']
  minor:
    labels: ['Enhancement', 'Feature', 'Dev Task']
  patch:
    labels: ['Bug', 'Hot Fix', 'Task']
  default: patch
exclude-labels:
  - 'Skip-Changelog'
template: |
  ## 🚀 Pre-release (Develop)
  
  $CHANGES
