name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
prerelease: false
include-pre-releases: false
search-labels:
  - '/^v\d+\.\d+\.\d+$/'
version-resolver:
  major:
    labels: ['Major']
  minor:
    labels: ['Enhancement', 'Feature', 'Dev Task']
  patch:
    labels: ['Bug', 'Hot Fix', 'Task']
  default: patch
exclude-labels:
  - 'Skip-Changelog'
template: |
  ## ✅ Stable Release (Main)
  $CHANGES
