name-template: 'v$RESOLVED_VERSION-dev'
tag-template: 'v$RESOLVED_VERSION-dev'
prerelease: true

version-resolver:
  major:
    labels: ['Major']
  minor:
    labels: ['Enhancement', 'Feature', 'Dev Task']
  patch:
    labels: ['Bug', 'Hot Fix', 'Task']
  default: patch

exclude-labels:
  - 'Skip-Changelog'

required-labels:
  - Publish

template: |
  ## 🚀 Pre-release (develop)
  $CHANGES
