name: Release Drafter Main

on:
  pull_request:
    types: [closed, labeled]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Stable Draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-main.yml
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Draft if Labeled
        if: ${{ contains(github.event.pull_request.labels.*.name, 'Publish') }}
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-main.yml
          commitish: main
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
